using UnityEngine;
using SanMonica.Data;

namespace SanMonica.Audio
{
    /// <summary>
    /// The San Monica radio band. Each station's music is composed and
    /// synthesised procedurally from its genre parameters - drums, bass, chords
    /// and a lead line over an original chord progression - so the soundtrack is
    /// generated by the game and carries no third-party rights.
    /// </summary>
    public static class MusicSynth
    {
        public const int SampleRate = ProceduralAudio.SampleRate;

        private static readonly int[] MinorScale = { 0, 2, 3, 5, 7, 8, 10 };
        private static readonly int[] DorianScale = { 0, 2, 3, 5, 7, 9, 10 };
        private static readonly int[] MajorScale = { 0, 2, 4, 5, 7, 9, 11 };

        private static readonly int[][] Progressions =
        {
            new[] { 0, 5, 3, 4 },
            new[] { 0, 3, 4, 4 },
            new[] { 0, 6, 3, 4 },
            new[] { 0, 4, 5, 3 },
            new[] { 0, 2, 5, 4 }
        };

        private static float NoteToHz(int semitone) => 440f * Mathf.Pow(2f, (semitone - 69) / 12f);

        private static float Saw(float phase) => (phase % 1f) * 2f - 1f;
        private static float Square(float phase, float duty = 0.5f) => (phase % 1f) < duty ? 1f : -1f;
        private static float Tri(float phase)
        {
            float p = phase % 1f;
            return p < 0.5f ? p * 4f - 1f : 3f - p * 4f;
        }

        private static float NoiseValue(ref uint state)
        {
            state ^= state << 13; state ^= state >> 17; state ^= state << 5;
            return (state & 0xFFFFFF) / 8388608f - 1f;
        }

        /// <summary>Renders one complete track. Long, so callers slice it across frames.</summary>
        public static float[] RenderTrack(RadioStationDefinition station, int trackSeed, float seconds = 46f)
        {
            int length = Mathf.RoundToInt(SampleRate * seconds);
            var data = new float[length];
            var rng = new SanMonica.Core.Rng(trackSeed);
            uint noiseState = (uint)(trackSeed * 2654435761u + 5u);

            float bpm = station.bpm * rng.Range(0.97f, 1.03f);
            float beat = 60f / bpm;
            float bar = beat * 4f;
            int[] scale = station.genre == "Punk" || station.genre == "Garage Rock" ? MinorScale
                        : station.genre == "Soul" || station.genre == "Cumbia" ? MajorScale
                        : station.genre == "Lo-fi Jazz" ? DorianScale : MinorScale;

            var progression = Progressions[rng.Range(0, Progressions.Length)];
            int root = station.rootNote + rng.Range(-2, 3);
            float energy = Mathf.Clamp01(station.energy);
            float distortion = Mathf.Clamp01(station.distortion);

            bool hasDrums = !station.talkOnly;
            bool hasLead = energy > 0.4f && !station.talkOnly;

            for (int i = 0; i < length; i++)
            {
                float t = i / (float)SampleRate;
                float barPos = (t / bar) % 1f;
                int barIndex = Mathf.FloorToInt(t / bar);
                int chordIndex = progression[barIndex % progression.Length];
                float beatPos = (t / beat) % 1f;
                int beatIndex = Mathf.FloorToInt(t / beat);

                float sample = 0f;

                // ---- chord pad ----
                for (int voice = 0; voice < 3; voice++)
                {
                    int degree = (chordIndex + voice * 2) % scale.Length;
                    int octave = 12 * (voice == 2 ? 1 : 0);
                    float hz = NoteToHz(root + 12 + scale[degree] + octave);
                    float detune = 1f + (voice - 1) * 0.004f;
                    float phase = t * hz * detune;
                    float value = station.genre == "Lo-fi Jazz" || station.genre == "Soul"
                        ? Tri(phase)
                        : Saw(phase) * 0.6f + Tri(phase) * 0.4f;
                    sample += value * 0.12f * Mathf.Lerp(0.7f, 1.1f, energy);
                }

                // ---- bass ----
                {
                    int degree = chordIndex % scale.Length;
                    float hz = NoteToHz(root - 12 + scale[degree]);
                    float pattern = station.genre == "Techno" ? (beatPos < 0.5f ? 1f : 0.4f)
                                  : station.genre == "Cumbia" ? (beatPos < 0.3f || (beatIndex % 2 == 1 && beatPos > 0.5f) ? 1f : 0.2f)
                                  : Mathf.Exp(-beatPos * 3.5f);
                    float value = Square(t * hz, 0.42f) * 0.55f + Mathf.Sin(2f * Mathf.PI * hz * t) * 0.45f;
                    sample += value * 0.30f * pattern;
                }

                // ---- lead / arpeggio ----
                if (hasLead)
                {
                    int step = Mathf.FloorToInt(t / (beat * 0.5f));
                    int degree = scale[(chordIndex + step * 2) % scale.Length];
                    float hz = NoteToHz(root + 24 + degree);
                    float env = Mathf.Exp(-((t / (beat * 0.5f)) % 1f) * 4.2f);
                    float value = Saw(t * hz) * 0.5f + Square(t * hz * 2f, 0.3f) * 0.2f;
                    sample += value * env * 0.16f * energy;
                }

                // ---- drums ----
                if (hasDrums)
                {
                    // kick on beats 1 and 3 (plus 4-on-the-floor for techno)
                    bool kick = station.genre == "Techno" ? true : (beatIndex % 4 == 0 || beatIndex % 4 == 2);
                    if (kick)
                    {
                        float env = Mathf.Exp(-beatPos * 18f);
                        float hz = Mathf.Lerp(120f, 45f, Mathf.Clamp01(beatPos * 6f));
                        sample += Mathf.Sin(2f * Mathf.PI * hz * (beatPos * beat)) * env * 0.55f;
                    }
                    // snare on 2 and 4
                    if (beatIndex % 4 == 1 || beatIndex % 4 == 3)
                    {
                        float env = Mathf.Exp(-beatPos * 24f);
                        sample += NoiseValue(ref noiseState) * env * 0.30f;
                        sample += Mathf.Sin(2f * Mathf.PI * 190f * (beatPos * beat)) * env * 0.12f;
                    }
                    // hats on eighths
                    float hatPos = (t / (beat * 0.5f)) % 1f;
                    float hatEnv = Mathf.Exp(-hatPos * 48f);
                    sample += NoiseValue(ref noiseState) * hatEnv * 0.10f * (0.5f + energy * 0.7f);
                }

                // ---- character ----
                if (distortion > 0.01f)
                {
                    float drive = 1f + distortion * 6f;
                    sample = Mathf.Clamp(sample * drive, -1.1f, 1.1f);
                    sample = sample - sample * sample * sample / 3f;
                }

                // Arrangement: drop the lead every fourth bar for breathing room.
                if ((barIndex % 8) == 7) sample *= Mathf.Lerp(1f, 0.55f, barPos);

                data[i] = sample * 0.34f;
            }

            // Soft limiter and loop-friendly fades.
            float peak = 0f;
            for (int i = 0; i < length; i++) peak = Mathf.Max(peak, Mathf.Abs(data[i]));
            if (peak > 0.0001f)
            {
                float scaleFactor = 0.88f / peak;
                for (int i = 0; i < length; i++) data[i] *= scaleFactor;
            }
            int fade = SampleRate / 2;
            for (int i = 0; i < fade && i < length; i++)
            {
                float k = i / (float)fade;
                data[i] *= k;
                data[length - 1 - i] *= k;
            }
            return data;
        }
    }
}
